language: node_js
node_js:
  - "6"
install:
  - npm install smild@~4.1.0 -g
  - npm install react@15.4.1 react-dom@15.4.1 react-router@3.0.0
  - npm install
script:
  - smild test
  - smild build
deploy:
  skip_cleanup: true
  provider: npm
  email: sysadmin@tierratelematics.com
  api_key:
    secure: MuoJdxOHoFt43jihFBrC/w8mfL21JNxWupc+ziR0d4Bq5WAQ+wYvjHR5tXDmdNywf77enH8XUu+XQLgQN8ofTQgn2CbyAkGtImgabv14FIe8YorQ3ynpW5i9TzUg3ax+3CR8d64ggQFWwwag+UcUrprcgjqPVQR+DlQRcv0/nky+Mrt1He9QSSJg7Q9+UN+GqjCJw6kFDyhzFrONSctfAjhuP6FBtaE3t6bEMZVKenw1J4e3yXT+vK0tPEUfHN/qjT2pKOL+OdcyY21DYnZCRML5Sxcwda9M3b5+hM8MAB5x/o6RtghOUN3sZZ0IkjpT5JYtjihRUS/8AF3Fu9or7lwK8yePaB9UHrJVnoWOrp3NFng2PD9PijAu9m4dOEcnpk+2ZFn3YrGFeeHAUnUjR6ajO1+YkYRFtb59mfRQsWWfKA9ihJhBvZj7geS1vgQpWOssWw/v3vFOFD+9M4rY2f+AAWp3ZfxecqDNjQ9MArBoR8OiGdCR0ZziGcXtLRJ29C5hRnqJDLWJg64L+dIqrnBTo0/gOZhPRPPpuVrQ7iwsn9o5marEXYQ4dxAhqSetNMIhi6QXoXzvy4BkWWPSX85r92U3JJAszZVi8xLcDcTOybIGVYm7UpIMDv3Q8uPDkz5G/k8d1cDfInNF6R0qptokvXOr/NF52P7XzXxsGX4=
  on:
    branch: master
    repo: tierratelematics/ninjagoat
    tags: false
notifications:
  slack:
    branch: develop
    tags: false
    secure: om/E6qN2AQVJxk6gJd3P7D6fsqF69o5aGaa5dSUUDR+CXJhWeqZwIsYI/r8ZXzd4uyFp2xRhXlGIoif11YoRxdIH2/+leyT1bBnP7AWgjrCqLAjadir7AeIOFbWeVZaTObAnepa68eiFUg+9KscCCLf409cv3vYi2e2rNKJcrLhRcKs9v3q0DGRnoocBZE4nq86WSDHgipDpIPml5LOJfmGLiyI7oVdwDJ7rEMHo6pqOtspN4yFFFHkfPwmyZvhp/XcY2Roz5cpUn/mhu/hnA3zqU+HZzqXL8Ddk9JBdH1fxMUibKXtOg7U5xiS9G4xdVd5eXjSXtP9iCehVwJcx7/1Ofk/DolG4ncXk+LCiNWZbifUcHzBcIRBBEQ/85bnZrpTZ7ZD85jE7CWJ6Nbklrrqj1MvSjf5J8NxW137FOz2xnKGqm8rZDFPo8140yaUAoKntzgXXzLeg/K+P49uoniKWEBFF5U7QTEwo8n9k0nQibnMkQiL/x118o2xE2h+8tvjEjj0QyPBXE9nJSxu/Gc6EuKeJ5BJXD3yZNvEPs360376Rj7mjoncOgCxZ0OmhRf6wrEdp5C3ehpZHdbgZ24lTLfLmFwYrCcr/ZG23TKUx2GfTjAnwFeM2hcZlMCnHb+yVqfn7MW2w/r5VRdDV8BcNLGIVwOGMHSQuRNkxZMk=
